### ISSUE TITLE
Initiative Tracker delete button does not always work with group-added creatures

### ISSUE THREAD

**Issue by alex-ball** [5etools-mirror-1/5etools-mirror-1.github.io#102]
Is this a bug or a feature request: Bug

Issue: Under certain circumstances, clicking on the delete icon (with no modifier key) at the end of a row in the Initiative Tracker has no effect. It seems to happen when multiple creatures are added in one go.

Page(s) affected: Initiative Tracker

Reproduction steps:

*Case 1:*

1. On a blank Initiative Tracker, add several instances of a creature in one go (e.g. 3 Giant Flies)
2. Edit the HP of the first one.
3. Select the delete button for the first one. It is removed as expected.
4. Select the delete button for any of the remaining monsters. Nothing happens.

*Case 2:*

1. On a blank Initiative Tracker, add several instances of a creature in one go (e.g. 3 Giant Flies)
2. Select the "Next turn" button
3. Edit the HP of the first monster (now no longer the current one).
4. Select the delete button for the first one. Nothing happens.
5. Select the delete button for any of the remaining monsters. Nothing happens.

Additional information:

I think this bug may have been introduced with the new Initiative Tracker code from [v1.182.0](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/releases/tag/v1.182.0): I first tried these steps on a cached copy of an older version and could not reproduce the bug, but after refreshing the page the bug manifested.

SHIFT + the delete button works as expected to remove all instances of the selected creature.

As a workaround, refreshing the page can cause an inoperative delete button to work again. (But you lose your scroll position on other panels you might have on the DM screen.)

Browser (Chromium, Firefox, Edge, etc): Vivaldi (Chromium), Firefox

Platform (Windows, iOS, Android, etc): macOS

**Comment by TheGiddyLimit** [comment]
Fixed for next release.
