### ISSUE TITLE
.zip for 1.143.0 appears damaged

### ISSUE THREAD

**Issue by QuantumParticles** [5etools-mirror-1/5etools-mirror-1.github.io#11]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:

Bug

Issue:

I am attempting to download 5etools 1.143.0 from this github so that I can host it locally for myself. I download 1.143.0 (it takes quite a bit) and when opening the zip file, WinRAR gave me an error message:

![image](https://user-images.githubusercontent.com/62723142/143648028-7805edba-07ab-4ff5-9e8b-f89fbf21318a.png)

Now, WinRAR has a built-in repair archive feature; which allowed me to extract the files. But when running the site with devd, there is no formatting and most of the data is still missing.

Page(s) affected:

https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/releases/tag/v1.143.0

Reproduction steps:

1) Download the source code from the link above (.zip)
2) Attempt to open the zip file with WinRAR

Additional information:

> Other zip files I've downloaded from completely different places still open fine.
> From what a quick google search told me, an unexpected end of archive error message is probably because the files are damaged somehow, either from an error while compressing on your end, or an error downloading on my end.
> Downloading on Microsoft Edge still produced the same error.

Browser (Chromium, Firefox, Edge, etc):

Google Chrome
Microsoft Edge

Platform (Windows, iOS, Android, etc):

Windows 10

**Comment by TheGiddyLimit** [comment]
Hot GitHub chooses to compress files is not something I have control over. It does, however, work just fine in 7zip.
