### ISSUE TITLE
Bug: Whirlwyrm should be a modified Giant Crocodile, not Crocodile.

### ISSUE THREAD

**Issue by Temp345bis** [5etools-mirror-1/5etools-mirror-1.github.io#119]
Is this a bug or a feature request: bug

Issue: whirlwyrm should copy data from "Giant Crocodile" (the CR5 critter), not from "Crocodile".
You can verify that [here](https://5etools-mirror-1.github.io/adventure.html#tofw,2,whirlwyrm%20attack,0)
Eh, the link does not seems to always take you to the right place, it's the "Whirlwyrm Attack" section of Chapter 9–Glorium: Heroes of the Day

Page(s) affected: bestiary.html#whirlwyrm_tofw (data/bestiary/bestiary-tofw.json file)

Fix: as simple as using "Giant Crocodile" instead of "Crocodile" in the "name" tag. The replaceTxt section can stay the same.

Tried to fix it myself but it's been a minute since I last used github. Sorry.

**Comment by TheGiddyLimit** [comment]
already been reported via Discord (the preferred channel for this sort of thing) and is fixed for next release
