### ISSUE TITLE
[Feature Request] Monster sounds

### ISSUE THREAD

**Issue by BenNelsonNeb** [5etools-mirror-1/5etools-mirror-1.github.io#120]
If you can't (or just don't want to) I understand, but I think the next cool thing will be monster sounds. "Monks Sound Enhancement" which plays an NPC sound when it is their turn in battle adds a lot and I feel it will become standard in the near future. Just like associating an image and a token to a creature, tie a small .ogg file that can be imported as well.  I am sure there will be a lot of arguments on what a blue dragon roar sounds like versus a black dragon, but that will be part of the fun. Maybe down the road, it will be tied to conditions, like if it's below half health it makes another sound or a different sound on death.  

I started tying sounds to creatures in my game that are used often, mostly beasts, bandits, pirates, and cultists.  There are a lot of open source sounds from old video games and just free sounds. but, listening to them, converting, uploading, and tying it to the creature is a lengthy process to do once.  If I need to reimport I would need to do it all over again. I love your tool, makes the process so easy, and it looks like you already have a way to tie sound to a creature with the "How to pronounce the creature name" option.  If you keep the standard the same as with an image I am sure Foundry and other modules (like Monks) will follow a simple format.

**Comment by TheGiddyLimit** [comment]
a couple standout problems here:

- sound files are (relatively) large. This would add a great deal of bloat to support a community-made module which (according to e.g. `https://img.shields.io/badge/dynamic/json?label=Forge%20Installs&query=package.installs&suffix=%25&url=https%3A%2F%2Fforge-vtt.com%2Fapi%2Fbazaar%2Fpackage%2Fmonks-sound-enhancements&colorB=4aa94a`) is far from universally used
- with the exception of VTT tokens, we stick to "official" content only. If WotC/etc. were to release a VTT sound pack for creatures, then I would look to integrate those. Anything unofficial, however, is not going to be put directly into Plutonium

if you, or some other enterprising soul, were to make a module which e.g. contained a mapping of `creature -> sound file` that a user could use to quickly/automatically add sounds to actors, then I would certainly consider supporting that module.

As an aside, Foundry is sensibly/reasonably strict with what they allow to be submitted as a module, so one would have to own the rights to all the sounds in one's module to make this viable. Sounds from old video games likely don't fall under that, although free sounds probably would.
