### ISSUE TITLE
iOS Webclip Dice Roller Position Cut Off

### ISSUE THREAD

**Issue by brennanmuir** [5etools-mirror-1/5etools-mirror-1.github.io#122]
Due to the curved corners of newer iPhones (issue noticed on iPhone 15 Pro Max), the Dice Roller pop-up caret in the lower right corner is cut off when 5etools is added as a web clip. 

This issue doesn't occur when 5etools is accessed in the browser due to the URL bar that fills the bottom of the screen. 

To recreate:
1. Open 5etools on Safari on an iPhone

2. Press the "Share" button in the bottom, center of the screen to open the Share menu

3. Select "Add to Home Screen"

4. Open the web clip that is now saved to your Home Screen. 

Suggested fix is to relocate the caret out of the corner.

![image](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/assets/18177606/908557b5-1c0d-43c2-b576-f9d69233fb2e)

**Comment by revilowaldow** [comment]
This was gone around in the discord previously, I remember Giddy trying to fix it and having issues.
Here's the link for convenience (patreon channel)
https://discord.com/channels/363680385336606740/600716832336379935/1059215245136105482
![image](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/assets/52298102/63295180-de9f-4789-bf2c-28dc02070f9b)

**Comment by TheGiddyLimit** [comment]
yup, and I'm still not buying an iPhone

if you, or anyone else, wants to submit a patch which doesn't impact supported platforms and alleviates the issue, then by all means

**Comment by revilowaldow** [comment]
> yup, and I'm still not buying an iPhone

It's definitely a sidequest, but you could hypothetically:
- https://github.com/sickcodes/Docker-OSX
- Install Xcode
- iPhone emulation

I'm not expecting this, just ensuring you're aware of the possibility.

**Comment by brennanmuir** [comment]
Appreciate you taking a look at this. It's the absolute lowest priority, I just wanted to at least document it. Thanks!

**Comment by nimids** [comment]
I just upgraded to a iPhone 15 and saw this, here's my solution.

 I added the following to the end of main.css:
```css
.rollbox-min{
    height:calc(24px + env(safe-area-inset-bottom, 0));
}
```
But that makes the box a little too tall so changed it to:
```css
.rollbox-min{
    height:calc(24px + calc(env(safe-area-inset-bottom, 0) / 2));
}
```
This looks just right to me it still clips the bottom right bit of the normal button but it's still easily visible and clickable on my iPhone 15.

Ideally you I would replace the `.rollbox-min`'s `height:24px;` but it's easier for me to append to the end of main.css in my mirroring solution. My only camera is my phone right now so I can't supply photos.

Desktop Chrome, Edge and Safari are unaffected. 
Webclip iPhone Safari is fixed.
Normal iPhone Safari is unaffected (it keeps the address bar down there).
iPhone Chrome seamlessly grows the buttom as it hides the bottom bar.

**Comment by TheGiddyLimit** [comment]
Sounds good, mind providing a screenshot of the results?

**Comment by revilowaldow** [comment]
![image](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/assets/52298102/6df69a61-cecc-4eb3-8d13-5a39c7412170)

It's challenging to screenshot as screenshots are saved without the physically cutoff corner being removed. In the app switcher you can screenshot it but it's fiddly. 

Difference between with and without the fix

![image](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/assets/52298102/fa9c0e99-af09-4200-bc6a-da2a9bbc6f4b)

![image](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/assets/52298102/68d4afb6-795e-449f-8d37-f22beff53c76)

**Comment by TheGiddyLimit** [comment]
ty, certainly looks more usable

**Comment by brennanmuir** [comment]
@TheGiddyLimit @revilowaldow Thank you both for fixing this. I don't log into github often so I didn't see the notification but I noticed the dice roller position had been fixed the other day! Again, thank you both for looking into this silly bug.
