### ISSUE TITLE
Importing encounters in initiative tracker removes additional columns

### ISSUE THREAD

**Issue by Mutant** [5etools-mirror-1/5etools-mirror-1.github.io#132]
Is this a bug or a feature request: bug

Issue: Importing encounters in initiative tracker removes additional columns

Page(s) affected: Initiative tracker on DMs screen

Reproduction steps:
1. Create an encounter
2. Add initiative tracker on DM screen
3. Add an additional column via settings (e.g. AC)
4. Import the encounter
5. The additional column is removed

**Comment by TheGiddyLimit** [comment]
fixed for next release

please do also switch to https://github.com/5etools-mirror-2/5etools-mirror-2.github.io ; this repo is no longer current
