### ISSUE TITLE
Race page purges homebrew content

### ISSUE THREAD

**Issue by anihacc** [5etools-mirror-1/5etools-mirror-1.github.io#21]
Is this a bug or a feature request: bug

Issue: Races page purges homebrew data

Page(s) affected: Races

Reproduction steps: download all necessary packages -> run powershell script to boot up the webserver -> go to books -> open up the homebrew screen and click "add all" -> go to races page. It should say "Error while loading homebrew! Purged homebrew data. (See the log for more information.)"

Additional information: I would provide the log if I knew where to find it

Browser (Chromium, Firefox, Edge, etc): opera GX

Platform (Windows, iOS, Android, etc): windows

**Comment by TheGiddyLimit** [comment]
Fixed for next release 👍 

Please report issues via our [Discord](https://discord.gg/5etools) in future; there's no guarantee they'll be seen here in a timely fashion
