### ISSUE TITLE
Locking the initiative tracker clears Additional Column values

### ISSUE THREAD

**Issue by scottTomaszewski** [5etools-mirror-1/5etools-mirror-1.github.io#23]
Is this a bug or a feature request: bug

Issue: In the initiative tracker when there are Additional Columns (AC, PP, etc) with values for Players, clicking the "Lock Tracker" button clears the values

Page(s) affected: DM Screen

Reproduction steps:
1. Add initiative tracker to DM screen
2. Add Player to Initiative tracker
2. Add Additional Column (ex: Armor class)
3. Set AC value for the player
4. click "Lock Tracker"
5.The value field for AC grays out and clears the value
Expectation is the textfield grays out, but value is preserved

Additional information: This tool is awesome, thanks!!

Browser (Chromium, Firefox, Edge, etc): Chrome

Platform (Windows, iOS, Android, etc): only tested on Linux, Ubuntu

**Comment by TheGiddyLimit** [comment]
Cheers, fixed for next release
