### ISSUE TITLE
Initiative tracker doesn't connect/load

### ISSUE THREAD

**Issue by FilterUnfiltered** [5etools-mirror-1/5etools-mirror-1.github.io#46]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: innittracker doesn't load

Page(s) affected: innittracker

Reproduction steps: Open innittracker on firefox or chrome, on linux. Try to connect to server.

Additional information: Using manjaro linux, latest version of firefox

Browser (Chromium, Firefox, Edge, etc): Firefox

Platform (Windows, iOS, Android, etc): Manjaro Linux

Here is the log from the browser console:
[5e.tools innittracker errorlog.txt](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/files/8882092/5e.tools.innittracker.errorlog.txt)

**Comment by TheGiddyLimit** [comment]
Looks like a caching issue. Check if it works in a different browser/incognito window!

**Comment by FilterUnfiltered** [comment]
> Looks like a caching issue. Check if it works in a different browser/incognito window!

It wasn't. It didn't work on chromium either, nor in incognito mode (chromium) nor private window (firefox)

**Comment by TheGiddyLimit** [comment]
I see. Does the `Manual (Legacy)` tab/mode work?

**Comment by FilterUnfiltered** [comment]
> I see. Does the `Manual (Legacy)` tab/mode work?

sorry for being gone, haven't had access to my pc in 2 weeks. No, the Legacy tab does not work either.
