### ISSUE TITLE
Add Book View to Magic Items

### ISSUE THREAD

**Issue by Tahlwyn** [5etools-mirror-1/5etools-mirror-1.github.io#47]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: 

Feature request.

Issue:

Consider adding the ability to display Magic Items in "Book View" similar to spells, complete with the ability to copy and export the selected items as markdown

**Comment by revilowaldow** [comment]
Consider joining the discord linked on the front page of the site where you can add to the list of suggestions. 
https://github.com/5etools/tracker

**Comment by TheGiddyLimit** [comment]
Implemented for next release
