### ISSUE TITLE
Dice rollel links in RPG cards content

### ISSUE THREAD

**Issue by m-radzikowski** [5etools-mirror-1/5etools-mirror-1.github.io#5]
Is this a bug or a feature request: feature / improvement

Issue: When you export JSON for RPG Cards Builder, dice stats in the creature actions section are exported with HTML `<span>` tag for dice roller. This makes the content less readable when you want to make some changes in beast description etc.

Page(s) affected: RPG Cards JSON Builder (makecards.html)

Reproduction steps:

1. Go to https://5e.tools/makecards.html
2. Add creature -> Acolyte
3. Export JSON
4. Go to https://crobi.github.io/rpg-cards/generator/generate.html
5. Load from file
6. See Contents textarea containing:

```
description | Club | <i>Melee Weapon Attack:</i> <span class="roller render-roller" title="Click to roll. SHIFT to roll with advantage, CTRL to roll with disadvantage."  onmousedown="event.preventDefault()" data-packed-dice='{&quot;type&quot;:&quot;dice&quot;,&quot;rollable&quot;:true,&quot;displayText&quot;:&quot;+2&quot;,&quot;toRoll&quot;:&quot;1d20+2&quot;,&quot;subType&quot;:&quot;d20&quot;,&quot;d20mod&quot;:&quot;+2&quot;,&quot;context&quot;:{&quot;type&quot;:&quot;hit&quot;}}' >+2</span> to hit, reach 5 ft., one target. <i>Hit:</i> 2 (<span class="roller render-roller" title="Click to roll. SHIFT to roll a critical hit, CTRL to half damage (rounding down)."  onmousedown="event.preventDefault()" data-packed-dice='{&quot;type&quot;:&quot;dice&quot;,&quot;rollable&quot;:true,&quot;toRoll&quot;:&quot;1d4&quot;,&quot;subType&quot;:&quot;damage&quot;}' >1d4</span>) bludgeoning damage.
```

Without `<span>` elements for dice roller (that are not useful here anyway), this text would be just:

```
description | Club | <i>Melee Weapon Attack:</i> +2 to hit, reach 5 ft., one target. <i>Hit:</i> 2 (1d4) bludgeoning damage.
```

Additional information:

I'm happy to make this change and submit a PR, just give me a green light to do so.

Also, I was not 100% sure that this is a valid repo for submitting issues/PRs for 5e.tools because of the name ("mirror-1"), but I did not find any else.

**Comment by TheGiddyLimit** [comment]
Fixed for next release, cheers 👍 

Fwiw, reporting issues in our Discord is preferred; I don't often check this repo.
