### ISSUE TITLE
Download is missing sw-injector.js

### ISSUE THREAD

**Issue by pludi** [5etools-mirror-1/5etools-mirror-1.github.io#58]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Download is missing `sw-injector.js`, even though it's referenced

Page(s) affected: All

Reproduction steps:

1. Download & unpack v1.167.8
2. Watch the `error.log` of the server

**Comment by revilowaldow** [comment]
See https://github.com/5etools-mirror-1/5etools-mirror-1.github.io#service-worker

**Comment by pludi** [comment]
1. Any specific reason it's not part of the download?
2. Could it be replaced by an empty file, if only to get rid of the error messages on the server?

**Comment by TheGiddyLimit** [comment]
This is intended.
1. The download is a "some assembly required" version (`npm i && npm run build`), to minimize the amount of junky auto-generated files included. If you want a fully pre-packaged ready-to-go version, you can use the [Docker image](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/pkgs/container/5etools)
2. I would recommend you run the above `npm i && npm run build` command(s), but yes, using a blank file will probably hide the error
