### ISSUE TITLE
Raising CR in for certain creatures deletes all creatures from encounter 

### ISSUE THREAD

**Issue by Sprinkles-GS** [5etools-mirror-1/5etools-mirror-1.github.io#71]
_Is this a bug or a feature request:_
Bug

_Issue:_
Raising certain creatures over their original CR causes all creatures to be removed from the encounter

_Page(s) affected:_
Beastiary Encounter mode

_Reproduction steps:_
Add any creature, Add Guardian Naga to encounter, edit CR to be be 2+ over original CR

_Additional information:_
Same issue occurs for spirit Naga and bone variants

_Browser (Chromium, Firefox, Edge, etc):_
Chromium

_Platform (Windows, iOS, Android, etc):_
Desktop (chrome) & Android (chrome)

**Comment by TheGiddyLimit** [comment]
Fixed for next release
