### ISSUE TITLE
Gods of the Yuan-Ti (VGtM) missing in Deities

### ISSUE THREAD

**Issue by Darthfett** [5etools-mirror-1/5etools-mirror-1.github.io#72]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Feature request?

Issue: The Gods listed in VGtM page Gods of the Yuan-Ti (https://5e.tools/book.html#vgm,0,gods%20of%20the%20yuan-ti,0) are missing in the Deities search

Page(s) affected: https://5e.tools/deities.html

Reproduction steps: Attempt to search for "Dendar" or "Merrshaulk" in the Deities page, and note that they are not listed.

Additional information:

Browser (Chromium, Firefox, Edge, etc): N/A (Firefox)

Platform (Windows, iOS, Android, etc): N/A (Windows)

**Comment by TheGiddyLimit** [comment]
Added for next release
