### ISSUE TITLE
Dockerfile in Releases failing to load php file

### ISSUE THREAD

**Issue by ajs5710** [5etools-mirror-1/5etools-mirror-1.github.io#75]
Steps to reproduce:
- Download 5etools-v1.174.3.zip from https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/releases/tag/v1.174.3
- Extract to folder
- cd into extracted folder
- docker build
- docker run
Then logs say `Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20151012/opcache:  /usr/local/lib/php/extensions/no-debug-non-zts-20151012/opcache: cannot open shared object file: No such file or directory`

Based on that path and some details here: https://serverfault.com/questions/399310/php-extensions-no-debug-non-zts-xxxxxxxx it seems that perhaps there are some php modules missing from alpine/the docker image.

**Comment by ajs5710** [comment]
Actually, this seems to be something to do with where I'm trying to deploy the docker container (as an azure web app).  Running locally on my macbook seems to work flawlessly.  Let me troubleshoot a bit more and I'll reopen with more details if it's something that needs fixed in the Dockerfile.

**Comment by ajs5710** [comment]
Turns out the issue for me was two fold. Firstly, windows sucks for development which made it hard for me to troubleshoot issues relating to the dockerfile.  Secondly, and more importantly, an azure container registry must have the admin account enabled in order to deploy as a web app: https://learn.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli#admin-account

**Comment by TheGiddyLimit** [comment]
Good to know, ty
