### ISSUE TITLE
Recipies: Can not change Servings

### ISSUE THREAD

**Issue by LocalNeckbeard** [5etools-mirror-1/5etools-mirror-1.github.io#81]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Can not change Servings in the Recipies Tab
 
Page(s) affected: Recipies

Reproduction steps: Within the Recipies Tab, switching Serving size does not change ingredient amounts, however the link does change

Additional information:

Browser (Chromium, Firefox, Edge, etc): Brave (Chromium Based)

Platform (Windows, iOS, Android, etc): Windows

**Comment by TheGiddyLimit** [comment]
fixed for next release
