### ISSUE TITLE
Night Hag skills

### ISSUE THREAD

**Issue by matejsen** [5etools-mirror-1/5etools-mirror-1.github.io#83]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: bug

Issue: Night Hag skills

Page(s) affected: Night Hag

Reproduction steps:

Additional information: Minor thing, but four listed skills of night hag should be 1 higher (Deception +7, Insight +6, Perception +6, Stealth +6). Even though the night hag doesn't follow the standard calculation formula for skills for whatever reason, the monsters doesn't have to follow it.

Browser (Chromium, Firefox, Edge, etc):

Platform (Windows, iOS, Android, etc):

**Comment by TheGiddyLimit** [comment]
> he monsters doesn't have to follow it

When it comes to WotC-published source books, they do. We maintain a small handful of "community patches" of this sort.
