### ISSUE TITLE
Can you please add all the "Sage Advice" question/answers and the text of any tweets from jeremy crawford that clarify RAW/RAI?

### ISSUE THREAD

**Issue by learningnewthingstoday** [5etools-mirror-1/5etools-mirror-1.github.io#88]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:  feature

**Comment by TheGiddyLimit** [comment]
The Sage Advice compendium can be found [here](https://5etools-mirror-1.github.io/book.html#sac); is it missing content?

As for keeping a curated summary of everything Crawford has ever tweeted, I'm afraid that's horrifically unsustainable.
