### ISSUE TITLE
Importing Large Amount of Entries causes "Out of Memory" error on browser.

### ISSUE THREAD

**Issue by JaysonMendoza** [5etools-mirror-1/5etools-mirror-1.github.io#90]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:

Issue:
When importing large amounts of records the procedure will crash at some arbitrary point when it hits the browsers assigned max memory limitation.

Page(s) affected: All importing

Reproduction steps:
Using Spells as example
1) Load chosen server and campaigin in Foundry VTT with 5etools active
2) Open up importer in items
3) Select Spells for 5etools data
4) Select import
5) Select all spells in new screen
6) Select import

This should begin and at some point before the end the browser will hit it's allocated hard memory limit.

Additional information:

Browser (Chromium, Firefox, Edge, etc):
Chrome Version 112.0.5615.121 (Official Build) (64-bit)
Edge Version 112.0.1722.48 (Official build) (64-bit)

Platform (Windows, iOS, Android, etc):
Windows

### **Suggested Solution**
This is likely the cause of a procedure that iterates through all records.
Considering the browser has hard limitations it would be better if the procedure was optomized to set an upper limit on memory load.

This can be accomplished by setting a limit on the number of active concurrent requests and then iterating through each record.

**Comment by revilowaldow** [comment]
Please report bugs with Plutonium in the community [discord](https://discord.gg/5etools) using the `/bugreport` command.
This is a repo for the website code, not plutonium, and bugs with the website are also preffered there.

Further, please consider the following information; we strongly advise against importing large amounts of content with Plutonium. It already fills the role of compendiums that is otherwise needed in Foundry, and having large levels of content directly in the game is not advised whether using Plutonium or not.

<hr>

> Some people want to import all the content into their D&D 5e game as soon as they get Plutonium. This is not recommended for the following reasons:
> 
 > 🔸Plutonium's data is all local. There is no need to import it all 'just in case'—once you install the module, all the data is there. Images are not, but you can easily preload them all from within Plutonium's config menu.
> 🔸 Once data is imported into your game, it becomes stagnant. However, Plutonium's data is constantly being improved: it gets typo fixes and new features with each update.
> 🔸 If you import character data directly to the sheet ![image](https://user-images.githubusercontent.com/52298102/233132487-d7873e33-410f-4974-bbe9-d9c225f9d02b.png) button at the top) rather than from a compendium, Plutonium has much more data to feed from and as such has its own workflow. This lets you choose things such as proficiencies, starting inventory, features, subclasses, etc.
> 🔸 If you import a great number of entries (+1500) directly into your game, this might cause higher loading times to everyone in it. Try to import only the content that you will soon use, or, if you definitely need the content in the game now (e.g. for interactions with other modules), it's recommended that you use compendiums instead. Plutonium lets you import directly into them.
> 🔸Further, for modules like "Quick Insert" Plutonium already inserts itself into their workflow without the need to use compendiums at all.

**Comment by JaysonMendoza** [comment]
This issue should be closed because it is regarding the module. A ticket was opened on the discord server.
