### ISSUE TITLE
Bypasses for some creatures are not correct

### ISSUE THREAD

**Issue by renzo38** [5etools-mirror-1/5etools-mirror-1.github.io#92]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: feature

Issue: Gargoyle, Flesh Golem, Clay Golem (probably some others) are `immuned` to magical attacks but are not supposed to

Page(s) affected: 

Reproduction steps: Import one of these creatures, open the `Damage Immunities` panel, `Magical` should be checked in the `Physical Bypasses` section

Additional information:

Browser (Chromium, Firefox, Edge, etc): Brave

Platform (Windows, iOS, Android, etc): Windows

**Comment by TheGiddyLimit** [comment]
Fixed for next release
