### ISSUE TITLE
Class feature Sorcerous Versatility has wrong link to cleric spell list

### ISSUE THREAD

**Issue by dachsei** [5etools-mirror-1/5etools-mirror-1.github.io#94]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: In class feature "Sorcerous Versatility|Sorcerer||4|TCE" the link to the cantrips go to the cleric spell list, but should link to the sorcerer list.

Page(s) affected: https://5e.tools/classes.html#sorcerer_phb,state:feature=s3-1

Reproduction steps: Open https://5e.tools/classes.html#sorcerer_phb,state:feature=s3-1 and click [sorcerer spell list](https://5e.tools/spells.html#blankhash,flstlevel:0=1,flstclass:cleric=1)

Additional information:

Browser (Chromium, Firefox, Edge, etc): All

Platform (Windows, iOS, Android, etc): All

**Comment by TheGiddyLimit** [comment]
fixed for next release
